spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/interview_scheduler?serverTimezone=UTC&useLegacyDatetimeCode=false&connectionTimeZone=SERVER}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Tanisha_21}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework: info

app:
  slot:
    generation-days: 14

